services:

  web1:
    build: 
      context: ./django/
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env/dev.env 

  web2:
    build: 
      context: ./django2/
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./django2/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose:
      - 8080
    env_file:
      - ./.env/dev.env 

  # webapp:
  #   build: 
  #     context: ./django/
  #   # command: python manage.py runserver 0.0.0.0:8000
  #   command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
  #   volumes:
  #     - ./django/:/usr/src/app/
  #     - static_files:/usr/src/app/staticfiles
  #   expose:
  #     - 8000
  #   env_file:
  #     - ./.env/dev.env 

  webserver:
    build:
      context: ./nginx/
    ports:
      - 80:80
    depends_on:
      - webapp
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles
      - ./nginx/v1/:/home/html/v1/
      - ./nginx/v2/:/home/html/v2/

volumes:
  static_files:

